"""
Project GOAT v0.7 — Scientific Feature Engineering Package

Exposes feature core models, metadata specifications, context validators,
canonical hash calculators, Scientific Feature Fingerprints, Capability Contracts,
abstract base classes, price primitives, Feature Registry, Dependency Graph DAG engine (GraphNode, GraphEdge),
Pre-Validation Quality Gate Framework, and Feature Space Exploration Engine (ExplorationDecision).
"""

from goat.features.core import (
    DEFAULT_FINGERPRINT_ALGORITHM,
    DEFAULT_FINGERPRINT_VERSION,
    BaseFeature,
    CompositeFeature,
    ComputationalConstraints,
    DataType,
    DeprecationStatus,
    DerivedFeature,
    DeterminismClass,
    ExecutionCostMetadata,
    FeatureCapabilityContract,
    FeatureInputContract,
    FeatureMetadata,
    FeatureOutputContract,
    MarketDataWindow,
    PrimitiveFeature,
    StationarityType,
    TaxonomyCategory,
    compute_feature_canonical_hash,
    compute_scientific_feature_fingerprint,
    validate_feature_capability_contract,
    validate_scientific_feature_fingerprint,
)
from goat.features.exploration import (
    AbsoluteTransform,
    BaseSearchStrategy,
    BaseTransformation,
    BayesianSearchAdapter,
    BeamSearchStrategy,
    CandidateFeature,
    DecisionValidationError,
    DifferenceTransform,
    EvolutionarySearchAdapter,
    ExhaustiveSearchStrategy,
    ExplorationBudget,
    ExplorationDecision,
    ExplorationReport,
    FeatureExplorationEngine,
    FeatureLineageEngine,
    GrammarGuidedSearchStrategy,
    LineageValidationError,
    LogTransform,
    ProductTransform,
    RatioTransform,
    RollingMeanTransform,
    RollingStdDevTransform,
    RuleBasedSearchStrategy,
    SignTransform,
    SymbolicSearchAdapter,
    TransformationRegistry,
    compute_candidate_id,
    compute_decision_id,
    compute_lineage_hash,
)
from goat.features.graph import (
    CircularDependencyError,
    FeatureDependencyGraph,
    GraphEdge,
    GraphNode,
    GraphValidationError,
    compute_edge_id,
    compute_node_id,
)
from goat.features.primitives import (
    BarRange,
    BodyRatio,
    LogReturn,
    LowerWickRatio,
    UpperWickRatio,
)
from goat.features.quality import (
    BaseQualityGate,
    ComplexityQualityGate,
    FeatureQualitySummaryReport,
    LeakageQualityGate,
    MulticollinearityQualityGate,
    NumericalStabilityQualityGate,
    QualityGatePipeline,
    QualityGateReport,
    QualityGateStatus,
    RegistryConsistencyQualityGate,
    StationarityQualityGate,
    VarianceQualityGate,
)
from goat.features.registry import (
    FeatureRegistryService,
    FeatureRegistryVerifier,
    RegistrationStatus,
    RegistryAuditEvent,
    RegistryRecord,
    SQLiteFeatureRepository,
    ValidationStatus,
)

__all__ = [
    # Core Domain & Metadata
    "TaxonomyCategory",
    "DataType",
    "DeterminismClass",
    "StationarityType",
    "DeprecationStatus",
    "FeatureMetadata",
    "MarketDataWindow",
    "compute_feature_canonical_hash",
    "compute_scientific_feature_fingerprint",
    "validate_scientific_feature_fingerprint",
    "DEFAULT_FINGERPRINT_ALGORITHM",
    "DEFAULT_FINGERPRINT_VERSION",
    # Capability Contracts
    "FeatureCapabilityContract",
    "ComputationalConstraints",
    "FeatureOutputContract",
    "FeatureInputContract",
    "ExecutionCostMetadata",
    "validate_feature_capability_contract",
    # Abstract Classes & Primitives
    "BaseFeature",
    "PrimitiveFeature",
    "DerivedFeature",
    "CompositeFeature",
    "LogReturn",
    "BarRange",
    "BodyRatio",
    "UpperWickRatio",
    "LowerWickRatio",
    # Feature Registry
    "RegistrationStatus",
    "ValidationStatus",
    "RegistryRecord",
    "RegistryAuditEvent",
    "SQLiteFeatureRepository",
    "FeatureRegistryVerifier",
    "FeatureRegistryService",
    # Dependency Graph Engine
    "GraphNode",
    "GraphEdge",
    "compute_node_id",
    "compute_edge_id",
    "FeatureDependencyGraph",
    "CircularDependencyError",
    "GraphValidationError",
    # Quality Gate Framework
    "QualityGateStatus",
    "QualityGateReport",
    "BaseQualityGate",
    "VarianceQualityGate",
    "StationarityQualityGate",
    "LeakageQualityGate",
    "NumericalStabilityQualityGate",
    "MulticollinearityQualityGate",
    "ComplexityQualityGate",
    "RegistryConsistencyQualityGate",
    "FeatureQualitySummaryReport",
    "QualityGatePipeline",
    # Feature Space Exploration Engine
    "BaseTransformation",
    "LogTransform",
    "AbsoluteTransform",
    "SignTransform",
    "RatioTransform",
    "DifferenceTransform",
    "ProductTransform",
    "RollingMeanTransform",
    "RollingStdDevTransform",
    "TransformationRegistry",
    "ExplorationDecision",
    "compute_decision_id",
    "DecisionValidationError",
    "CandidateFeature",
    "compute_candidate_id",
    "FeatureLineageEngine",
    "LineageValidationError",
    "compute_lineage_hash",
    "ExplorationBudget",
    "BaseSearchStrategy",
    "ExhaustiveSearchStrategy",
    "RuleBasedSearchStrategy",
    "GrammarGuidedSearchStrategy",
    "BeamSearchStrategy",
    "BayesianSearchAdapter",
    "EvolutionarySearchAdapter",
    "SymbolicSearchAdapter",
    "FeatureExplorationEngine",
    "ExplorationReport",
]
