"""
Project GOAT v0.8 — Trade Lifecycle Core Enumerations
"""

from enum import Enum


class TradeState(str, Enum):
    """Trade lifecycle state enumeration."""
    CREATED = "CREATED"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    OPEN = "OPEN"
    MODIFIED = "MODIFIED"
    SL_UPDATED = "SL_UPDATED"
    TP_UPDATED = "TP_UPDATED"
    TRAILING_UPDATED = "TRAILING_UPDATED"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class TradeEventType(str, Enum):
    """Trade event classification enumeration."""
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    BROKER_ACCEPTED = "BROKER_ACCEPTED"
    BROKER_REJECTED = "BROKER_REJECTED"
    PARTIAL_FILL = "PARTIAL_FILL"
    COMPLETE_FILL = "COMPLETE_FILL"
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_MODIFIED = "POSITION_MODIFIED"
    STOP_LOSS_UPDATED = "STOP_LOSS_UPDATED"
    TAKE_PROFIT_UPDATED = "TAKE_PROFIT_UPDATED"
    TRAILING_STOP_UPDATED = "TRAILING_STOP_UPDATED"
    PARTIAL_CLOSE = "PARTIAL_CLOSE"
    COMPLETE_CLOSE = "COMPLETE_CLOSE"
    EXECUTION_FAILURE = "EXECUTION_FAILURE"
    MANUAL_CLOSE = "MANUAL_CLOSE"
    AUTOMATIC_CLOSE = "AUTOMATIC_CLOSE"


class LifecycleAuditEventType(str, Enum):
    """Lifecycle audit event category enumeration."""
    LIFECYCLE_CREATED = "LIFECYCLE_CREATED"
    STATE_TRANSITION = "STATE_TRANSITION"
    EVENT_RECORDED = "EVENT_RECORDED"
    RECONCILIATION_AUDIT = "RECONCILIATION_AUDIT"
    ANOMALY_DETECTED = "ANOMALY_DETECTED"


class TradeReconciliationMismatchType(str, Enum):
    """Trade lifecycle reconciliation discrepancy types."""
    ORPHAN_EXECUTION = "ORPHAN_EXECUTION"
    ORPHAN_POSITION = "ORPHAN_POSITION"
    MISSING_FILL = "MISSING_FILL"
    DUPLICATE_FILL = "DUPLICATE_FILL"
    VOLUME_MISMATCH = "VOLUME_MISMATCH"
    EXECUTION_MISMATCH = "EXECUTION_MISMATCH"
    MISSING_CLOSE = "MISSING_CLOSE"
    INCONSISTENT_LIFECYCLE = "INCONSISTENT_LIFECYCLE"
