"""
Project GOAT v0.7 — Quality Gate Framework Base Specifications

Defines QualityGateStatus, QualityGateReport model, and BaseQualityGate abstract class.
"""

from __future__ import annotations

import abc
import enum
from typing import Any

from pydantic import BaseModel, Field

from goat.features.core.base import BaseFeature
from goat.features.core.context import MarketDataWindow


class QualityGateStatus(str, enum.Enum):
    """Execution outcome status for a Quality Gate."""
    PASSED = "passed"
    FAILED = "failed"
    SKIPPED = "skipped"


class QualityGateReport(BaseModel):
    """Immutable report generated by a single Quality Gate evaluation."""

    gate_id: str = Field(..., description="Unique identifier of the quality gate")
    gate_version: str = Field(default="1.0.0", description="Quality gate implementation version")
    status: QualityGateStatus = Field(..., description="Evaluation outcome status")
    reason: str = Field(..., description="Explanation of evaluation outcome")
    scientific_notes: str = Field(default="", description="Scientific notes or threshold metrics")
    timestamp: str = Field(..., description="ISO-8601 UTC evaluation timestamp")
    details: dict[str, Any] = Field(default_factory=dict, description="Detailed test statistics")

    class Config:
        frozen = True
        extra = "forbid"


class BaseQualityGate(abc.ABC):
    """Abstract base class for all pluggable Quality Gates in Project GOAT."""

    def __init__(self, gate_id: str, gate_version: str = "1.0.0") -> None:
        self._gate_id = gate_id
        self._gate_version = gate_version

    @property
    def gate_id(self) -> str:
        """Return unique gate identifier."""
        return self._gate_id

    @property
    def gate_version(self) -> str:
        """Return gate version."""
        return self._gate_version

    @abc.abstractmethod
    def evaluate(
        self,
        feature: BaseFeature,
        context: MarketDataWindow | None = None,
    ) -> QualityGateReport:
        """Evaluate candidate feature against quality gate criteria.

        Args:
            feature: Target BaseFeature instance.
            context: Optional MarketDataWindow dataset for statistical evaluation.

        Returns:
            Immutable QualityGateReport.
        """
        ...
