"""
Project GOAT Phase 7 — Research Report & Reasoning Domain Models

Defines immutable Pydantic models for structured research conclusions, reports, and explanation persona levels.
"""

from __future__ import annotations

from enum import Enum
from typing import Any
from pydantic import BaseModel, Field

from goat.ai_reasoning.models.evidence import EvidenceBundle
from goat.research.edge.canonical import compute_canonical_sha256


class ExplanationLevel(str, Enum):
    """Target persona levels for natural language quantitative research explanations."""
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    PROFESSIONAL_QUANT = "PROFESSIONAL_QUANT"


class ReasoningConclusion(BaseModel):
    """Immutable single research deduction generated by the deterministic ReasoningEngine."""

    conclusion_id: str = Field(..., description="Unique conclusion ID formatted as CON_<HEX16>", pattern=r"^CON_[A-Fa-f0-9]{16}$")
    claim: str = Field(..., description="Deduction statement claim")
    status_verdict: str = Field(..., description="Verdict status (e.g. ACTIVE, VALIDATED, FAILED, DEGRADING)")
    reasoning_steps: list[str] = Field(..., description="Ordered deterministic logical proof steps")
    supporting_evidence_ids: list[str] = Field(..., description="IDs of evidence records backing this claim")
    confidence_score: float = Field(..., description="Confidence score [0.0, 1.0]")

    class Config:
        frozen = True
        extra = "forbid"


class ResearchReport(BaseModel):
    """Immutable domain model representing an automated research report."""

    report_id: str = Field(..., description="Unique research report ID formatted as REP_<HEX16>", pattern=r"^REP_[A-Fa-f0-9]{16}$")
    title: str = Field(..., description="Descriptive research report title")
    timestamp: str = Field(..., description="ISO 8601 UTC report generation timestamp")
    explanation_level: ExplanationLevel = Field(default=ExplanationLevel.PROFESSIONAL_QUANT, description="Persona target level")
    executive_summary: str = Field(..., description="High-level synthesis of research findings")
    conclusions: list[ReasoningConclusion] = Field(..., description="List of deterministic conclusions")
    evidence_bundle: EvidenceBundle = Field(..., description="Aggregated evidence bundle backing findings")
    supporting_statistics: dict[str, float] = Field(..., description="Key numerical metrics summary")
    risk_factors: list[str] = Field(..., description="Identified risk factors & drawdown considerations")
    limitations: list[str] = Field(..., description="Sample size, regime, or distribution assumptions/limitations")
    recommended_next_steps: list[str] = Field(..., description="Quantitative next steps for research governance")
    checksum: str = Field(..., description="SHA-256 canonical digest")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Extensible operational metadata")
    canonical_hash: str = Field(..., description="Full SHA-256 canonical hash digest")

    class Config:
        frozen = True
        extra = "forbid"


def compute_conclusion_id(claim: str, status_verdict: str) -> tuple[str, str]:
    """Compute deterministic conclusion_id and canonical_hash for a ReasoningConclusion."""
    payload = {"claim": claim.strip(), "status_verdict": status_verdict.strip()}
    digest = compute_canonical_sha256(payload)
    return f"CON_{digest[:16].upper()}", digest.upper()


def compute_report_id(title: str, timestamp: str, target_id: str) -> tuple[str, str]:
    """Compute deterministic report_id and canonical_hash for a ResearchReport."""
    payload = {"target_id": target_id.strip(), "timestamp": timestamp.strip(), "title": title.strip()}
    digest = compute_canonical_sha256(payload)
    return f"REP_{digest[:16].upper()}", digest.upper()
