"""
Project GOAT v0.9 — Deriv Market Microstructure Enums
"""

from enum import Enum


class SyntheticIndexType(str, Enum):
    """Deriv Synthetic Index Categories & Instruments."""
    VOLATILITY_10 = "VOLATILITY_10"
    VOLATILITY_25 = "VOLATILITY_25"
    VOLATILITY_50 = "VOLATILITY_50"
    VOLATILITY_75 = "VOLATILITY_75"
    VOLATILITY_100 = "VOLATILITY_100"
    VOLATILITY_10_1S = "VOLATILITY_10_1S"
    VOLATILITY_25_1S = "VOLATILITY_25_1S"
    VOLATILITY_50_1S = "VOLATILITY_50_1S"
    VOLATILITY_75_1S = "VOLATILITY_75_1S"
    VOLATILITY_100_1S = "VOLATILITY_100_1S"
    BOOM_300 = "BOOM_300"
    BOOM_500 = "BOOM_500"
    BOOM_1000 = "BOOM_1000"
    CRASH_300 = "CRASH_300"
    CRASH_500 = "CRASH_500"
    CRASH_1000 = "CRASH_1000"
    JUMP_10 = "JUMP_10"
    JUMP_25 = "JUMP_25"
    JUMP_50 = "JUMP_50"
    JUMP_75 = "JUMP_75"
    JUMP_100 = "JUMP_100"
    STEP_INDEX = "STEP_INDEX"


class ObservationCategory(str, Enum):
    """Categories of Microstructure Observations."""
    VOLATILITY = "VOLATILITY"
    JUMP = "JUMP"
    LIQUIDITY = "LIQUIDITY"
    EXECUTION = "EXECUTION"
    MARKET_PROFILE = "MARKET_PROFILE"


class MicrostructureMetricType(str, Enum):
    """Types of measured market microstructure metrics."""
    REALIZED_VOLATILITY = "REALIZED_VOLATILITY"
    VOLATILITY_CLUSTERING = "VOLATILITY_CLUSTERING"
    VOLATILITY_PERSISTENCE = "VOLATILITY_PERSISTENCE"
    VOLATILITY_EXPANSION = "VOLATILITY_EXPANSION"
    VOLATILITY_CONTRACTION = "VOLATILITY_CONTRACTION"
    JUMP_FREQUENCY = "JUMP_FREQUENCY"
    JUMP_MAGNITUDE = "JUMP_MAGNITUDE"
    JUMP_SPACING = "JUMP_SPACING"
    JUMP_PERSISTENCE = "JUMP_PERSISTENCE"
    JUMP_CLUSTERING = "JUMP_CLUSTERING"
    SPREAD_STABILITY = "SPREAD_STABILITY"
    QUOTE_CONTINUITY = "QUOTE_CONTINUITY"
    TICK_DENSITY = "TICK_DENSITY"
    MARKET_ACTIVITY = "MARKET_ACTIVITY"
    EXECUTION_LATENCY = "EXECUTION_LATENCY"
    FILL_TIMING = "FILL_TIMING"
    EXECUTION_CONSISTENCY = "EXECUTION_CONSISTENCY"
    BROKER_RESPONSE_METRIC = "BROKER_RESPONSE_METRIC"


class JumpDirection(str, Enum):
    """Direction of observed price jumps."""
    UPWARD = "UPWARD"
    DOWNWARD = "DOWNWARD"
    NEUTRAL = "NEUTRAL"


class VolatilityRegime(str, Enum):
    """Classified Volatility Regime."""
    LOW_VOLATILITY = "LOW_VOLATILITY"
    NORMAL_VOLATILITY = "NORMAL_VOLATILITY"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    EXTREME_VOLATILITY = "EXTREME_VOLATILITY"
    EXPANDING = "EXPANDING"
    CONTRACTING = "CONTRACTING"


class ExecutionQualityRating(str, Enum):
    """Rating of measured broker execution characteristics."""
    EXCELLENT = "EXCELLENT"
    NORMAL = "NORMAL"
    DEGRADED = "DEGRADED"
    POOR = "POOR"
