"""
Project GOAT v0.7 — Mathematical Transformation Operators

Defines concrete immutable transformation operators (Unary, Binary, Rolling) for feature exploration.
"""

from __future__ import annotations

from typing import Any

import numpy as np

from goat.features.core.base import BaseFeature, CompositeFeature, DerivedFeature
from goat.features.core.context import MarketDataWindow
from goat.features.core.enums import StationarityType, TaxonomyCategory
from goat.features.exploration.transformations.base import BaseTransformation

EPSILON = 1e-12


# ---------------------------------------------------------------------------
# Unary Transformations
# ---------------------------------------------------------------------------

class TransformedUnaryFeature(DerivedFeature):
    """Derived feature wrapper generated by a unary transformation operator."""

    def __init__(
        self,
        parent: BaseFeature,
        op_name: str,
        op_func: Any,
        math_def: str,
        algorithmic_spec: str,
        lookback_window: int = 1,
    ) -> None:
        self._parent = parent
        self._op_func = op_func
        name = f"{op_name}_{parent.name}"
        super().__init__(
            lookback_window=lookback_window,
            name=name,
            version="1.0.0",
            taxonomy_category=parent.metadata.taxonomy_category,
            taxonomy_subcategory=f"transformed_{op_name.lower()}",
            mathematical_definition=math_def,
            algorithmic_spec=algorithmic_spec,
            dependencies=[parent.feature_id],
            expected_stationarity=parent.metadata.expected_stationarity,
        )

    def compute(self, context: MarketDataWindow) -> np.ndarray:
        parent_out = self._parent.compute(context)
        return self._op_func(parent_out)

    def to_ast_dict(self) -> dict[str, Any]:
        return {
            "op": self._name,
            "parent_ast": self._parent.to_ast_dict(),
            "version": self._version,
        }

    def _get_input_requirements(self) -> dict[str, Any]:
        reqs = self._parent._get_input_requirements()
        reqs["min_bars"] = max(reqs.get("min_bars", 1), self._lookback_window)
        return reqs


class LogTransform(BaseTransformation):
    """Logarithmic transformation: ln(|f| + epsilon)."""

    def __init__(self) -> None:
        super().__init__(
            name="LogTransform",
            version="1.0.0",
            scientific_description="Logarithmic transformation smoothing exponential variance",
            mathematical_definition=r"f_{\text{out}} = \ln(|f_{\text{in}}| + \epsilon)",
        )

    def transform(self, parents: list[BaseFeature]) -> BaseFeature:
        if len(parents) != 1:
            raise ValueError("LogTransform requires exactly 1 parent feature")
        p = parents[0]
        return TransformedUnaryFeature(
            parent=p,
            op_name="Log",
            op_func=lambda arr: np.log(np.abs(arr) + EPSILON),
            math_def=r"\ln(|" + p.metadata.mathematical_definition + r"| + \epsilon)",
            algorithmic_spec=f"np.log(np.abs({p.name}) + 1e-12)",
        )


class AbsoluteTransform(BaseTransformation):
    """Absolute value transformation: |f|."""

    def __init__(self) -> None:
        super().__init__(
            name="AbsoluteTransform",
            version="1.0.0",
            scientific_description="Absolute magnitude transformation removing directional sign",
            mathematical_definition=r"f_{\text{out}} = |f_{\text{in}}|",
        )

    def transform(self, parents: list[BaseFeature]) -> BaseFeature:
        if len(parents) != 1:
            raise ValueError("AbsoluteTransform requires exactly 1 parent feature")
        p = parents[0]
        return TransformedUnaryFeature(
            parent=p,
            op_name="Abs",
            op_func=lambda arr: np.abs(arr),
            math_def=r"|" + p.metadata.mathematical_definition + r"|",
            algorithmic_spec=f"np.abs({p.name})",
        )


class SignTransform(BaseTransformation):
    """Sign direction transformation: sign(f)."""

    def __init__(self) -> None:
        super().__init__(
            name="SignTransform",
            version="1.0.0",
            scientific_description="Sign direction extraction returning {-1, 0, 1}",
            mathematical_definition=r"f_{\text{out}} = \text{sign}(f_{\text{in}})",
        )

    def transform(self, parents: list[BaseFeature]) -> BaseFeature:
        if len(parents) != 1:
            raise ValueError("SignTransform requires exactly 1 parent feature")
        p = parents[0]
        return TransformedUnaryFeature(
            parent=p,
            op_name="Sign",
            op_func=lambda arr: np.sign(arr),
            math_def=r"\text{sign}(" + p.metadata.mathematical_definition + r")",
            algorithmic_spec=f"np.sign({p.name})",
        )


# ---------------------------------------------------------------------------
# Binary Transformations
# ---------------------------------------------------------------------------

class TransformedBinaryFeature(CompositeFeature):
    """Composite feature wrapper generated by a binary transformation operator."""

    def __init__(
        self,
        p1: BaseFeature,
        p2: BaseFeature,
        op_name: str,
        op_func: Any,
        math_def: str,
        algorithmic_spec: str,
    ) -> None:
        self._op_func = op_func
        name = f"{op_name}_{p1.name}_{p2.name}"
        super().__init__(
            upstream_features=[p1, p2],
            name=name,
            version="1.0.0",
            taxonomy_category=TaxonomyCategory.COMPOSITE,
            taxonomy_subcategory=f"binary_{op_name.lower()}",
            mathematical_definition=math_def,
            algorithmic_spec=algorithmic_spec,
            expected_stationarity=StationarityType.STATIONARY,
        )

    def compute(self, context: MarketDataWindow) -> np.ndarray:
        out1 = self._upstream_features[0].compute(context)
        out2 = self._upstream_features[1].compute(context)
        return self._op_func(out1, out2)

    def to_ast_dict(self) -> dict[str, Any]:
        return {
            "op": self._name,
            "parents_ast": [f.to_ast_dict() for f in self._upstream_features],
            "version": self._version,
        }

    def _get_input_requirements(self) -> dict[str, Any]:
        reqs1 = self._upstream_features[0]._get_input_requirements()
        reqs2 = self._upstream_features[1]._get_input_requirements()
        min_bars = max(reqs1.get("min_bars", 1), reqs2.get("min_bars", 1))
        cols = list(set(reqs1.get("required_columns", [])) | set(reqs2.get("required_columns", [])))
        return {"min_bars": min_bars, "required_columns": cols}


class RatioTransform(BaseTransformation):
    """Ratio transformation: f1 / max(|f2|, epsilon)."""

    def __init__(self) -> None:
        super().__init__(
            name="RatioTransform",
            version="1.0.0",
            scientific_description="Relative ratio construction between two feature series",
            mathematical_definition=r"f_{\text{out}} = \frac{f_1}{\max(|f_2|, \epsilon)}",
        )

    def transform(self, parents: list[BaseFeature]) -> BaseFeature:
        if len(parents) != 2:
            raise ValueError("RatioTransform requires exactly 2 parent features")
        p1, p2 = parents[0], parents[1]
        return TransformedBinaryFeature(
            p1=p1,
            p2=p2,
            op_name="Ratio",
            op_func=lambda a, b: a / np.maximum(np.abs(b), EPSILON),
            math_def=r"\frac{" + p1.metadata.mathematical_definition + r"}{\max(|" + p2.metadata.mathematical_definition + r"|, \epsilon)}",
            algorithmic_spec=f"{p1.name} / max(abs({p2.name}), 1e-12)",
        )


class DifferenceTransform(BaseTransformation):
    """Difference transformation: f1 - f2."""

    def __init__(self) -> None:
        super().__init__(
            name="DifferenceTransform",
            version="1.0.0",
            scientific_description="Linear difference construction between two feature series",
            mathematical_definition=r"f_{\text{out}} = f_1 - f_2",
        )

    def transform(self, parents: list[BaseFeature]) -> BaseFeature:
        if len(parents) != 2:
            raise ValueError("DifferenceTransform requires exactly 2 parent features")
        p1, p2 = parents[0], parents[1]
        return TransformedBinaryFeature(
            p1=p1,
            p2=p2,
            op_name="Diff",
            op_func=lambda a, b: a - b,
            math_def=r"(" + p1.metadata.mathematical_definition + r" - " + p2.metadata.mathematical_definition + r")",
            algorithmic_spec=f"{p1.name} - {p2.name}",
        )


class ProductTransform(BaseTransformation):
    """Interaction product transformation: f1 * f2."""

    def __init__(self) -> None:
        super().__init__(
            name="ProductTransform",
            version="1.0.0",
            scientific_description="Non-linear interaction product between two feature series",
            mathematical_definition=r"f_{\text{out}} = f_1 \cdot f_2",
        )

    def transform(self, parents: list[BaseFeature]) -> BaseFeature:
        if len(parents) != 2:
            raise ValueError("ProductTransform requires exactly 2 parent features")
        p1, p2 = parents[0], parents[1]
        return TransformedBinaryFeature(
            p1=p1,
            p2=p2,
            op_name="Product",
            op_func=lambda a, b: a * b,
            math_def=r"(" + p1.metadata.mathematical_definition + r" \cdot " + p2.metadata.mathematical_definition + r")",
            algorithmic_spec=f"{p1.name} * {p2.name}",
        )


# ---------------------------------------------------------------------------
# Rolling Transformations
# ---------------------------------------------------------------------------

class RollingMeanTransform(BaseTransformation):
    """Rolling mean temporal transformation over window N."""

    def __init__(self, window: int = 10) -> None:
        self._window = window
        super().__init__(
            name=f"RollingMean_{window}",
            version="1.0.0",
            scientific_description=f"Rolling temporal mean over window N={window}",
            mathematical_definition=r"\text{EMA}_N(f)",
            parameters={"window": window},
        )

    def transform(self, parents: list[BaseFeature]) -> BaseFeature:
        if len(parents) != 1:
            raise ValueError("RollingMeanTransform requires exactly 1 parent feature")
        p = parents[0]
        w = self._window

        def compute_mean(arr: np.ndarray) -> np.ndarray:
            if len(arr) == 0:
                return np.array([], dtype=np.float64)
            res = np.zeros_like(arr, dtype=np.float64)
            for i in range(len(arr)):
                start = max(0, i - w + 1)
                res[i] = np.mean(arr[start : i + 1])
            return res

        return TransformedUnaryFeature(
            parent=p,
            op_name=f"RollMean{w}",
            op_func=compute_mean,
            math_def=r"\text{Mean}_{" + str(w) + r"}(" + p.metadata.mathematical_definition + r")",
            algorithmic_spec=f"rolling_mean({p.name}, window={w})",
            lookback_window=w,
        )


class RollingStdDevTransform(BaseTransformation):
    """Rolling standard deviation temporal transformation over window N."""

    def __init__(self, window: int = 10) -> None:
        self._window = window
        super().__init__(
            name=f"RollingStdDev_{window}",
            version="1.0.0",
            scientific_description=f"Rolling temporal volatility dispersion over window N={window}",
            mathematical_definition=r"\sigma_N(f)",
            parameters={"window": window},
        )

    def transform(self, parents: list[BaseFeature]) -> BaseFeature:
        if len(parents) != 1:
            raise ValueError("RollingStdDevTransform requires exactly 1 parent feature")
        p = parents[0]
        w = self._window

        def compute_std(arr: np.ndarray) -> np.ndarray:
            if len(arr) == 0:
                return np.array([], dtype=np.float64)
            res = np.zeros_like(arr, dtype=np.float64)
            for i in range(len(arr)):
                start = max(0, i - w + 1)
                sub = arr[start : i + 1]
                res[i] = np.std(sub) if len(sub) > 1 else 0.0
            return res

        return TransformedUnaryFeature(
            parent=p,
            op_name=f"RollStd{w}",
            op_func=compute_std,
            math_def=r"\sigma_{" + str(w) + r"}(" + p.metadata.mathematical_definition + r")",
            algorithmic_spec=f"rolling_std({p.name}, window={w})",
            lookback_window=w,
        )
