"""
Project GOAT v1.0 — Live Multi-Timeframe Candle Builder

Aggregates continuous LiveTick streams into deterministic, non-duplicating OHLCV candles
across supported timeframes: 1M, 5M, 15M, 30M, 1H, 4H, 1D.
"""

from __future__ import annotations

import datetime
from datetime import timezone
import sqlite3
import json
from typing import Sequence

from goat.market_data.models.candle import MarketCandle, MarketTimeframe
from goat.market_data.models.tick import LiveTick
from goat.marketdata.core.canonical import compute_candle_id
from goat.research.edge.canonical import compute_canonical_sha256


TIMEFRAME_SECONDS: dict[str, int] = {
    "1M": 60,
    "5M": 300,
    "15M": 900,
    "30M": 1800,
    "1H": 3600,
    "4H": 14400,
    "1D": 86400,
}


def floor_timestamp_to_interval(epoch_sec: int, timeframe_str: str) -> tuple[str, str]:
    """Floor epoch seconds to interval start and calculate close timestamp.

    Returns:
        Tuple of (open_timestamp_iso, close_timestamp_iso)
    """
    sec = TIMEFRAME_SECONDS.get(timeframe_str, 60)
    interval_start_epoch = (epoch_sec // sec) * sec
    interval_end_epoch = interval_start_epoch + sec

    open_dt = datetime.datetime.fromtimestamp(interval_start_epoch, tz=timezone.utc)
    close_dt = datetime.datetime.fromtimestamp(interval_end_epoch, tz=timezone.utc)

    return open_dt.isoformat(), close_dt.isoformat()


def init_live_market_candles_db(conn: sqlite3.Connection) -> None:
    """Ensure live_market_candles table exists in SQLite database."""
    with conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS live_market_candles (
                candle_id TEXT PRIMARY KEY,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                open REAL NOT NULL,
                high REAL NOT NULL,
                low REAL NOT NULL,
                close REAL NOT NULL,
                volume REAL NOT NULL,
                open_timestamp TEXT NOT NULL,
                close_timestamp TEXT NOT NULL,
                completed INTEGER NOT NULL,
                checksum TEXT NOT NULL,
                metadata_json TEXT NOT NULL,
                canonical_hash TEXT NOT NULL
            );
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_live_candles_sym_tf ON live_market_candles (symbol, timeframe);"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_live_candles_open_ts ON live_market_candles (open_timestamp);"
        )


class LiveCandleBuilder:
    """Thread-safe, replay-deterministic multi-timeframe candle aggregator."""

    def __init__(
        self,
        db_conn: sqlite3.Connection | None = None,
        timeframes: Sequence[str] = ("1M", "5M", "15M", "30M", "1H", "4H", "1D"),
    ):
        self.timeframes = [tf.upper() for tf in timeframes]
        self.db_conn = db_conn

        if self.db_conn:
            init_live_market_candles_db(self.db_conn)

        # Forming candles state: (symbol, timeframe) -> dict representation
        self._forming_candles: dict[tuple[str, str], dict] = {}
        # In-memory history for quick queries: (symbol, timeframe) -> list[MarketCandle]
        self._history: dict[tuple[str, str], list[MarketCandle]] = {}

    def process_tick(self, tick: LiveTick) -> list[MarketCandle]:
        """Aggregate tick into forming candles across all supported timeframes.

        Returns:
            List of completed MarketCandle bars generated by this tick.
        """
        sym = tick.symbol.strip().upper()
        price = tick.price
        epoch = tick.epoch_timestamp
        completed_candles: list[MarketCandle] = []

        for tf in self.timeframes:
            key = (sym, tf)
            open_iso, close_iso = floor_timestamp_to_interval(epoch, tf)

            forming = self._forming_candles.get(key)

            if forming is None:
                # Initialize new forming candle for interval
                self._forming_candles[key] = {
                    "symbol": sym,
                    "timeframe": tf,
                    "open": price,
                    "high": price,
                    "low": price,
                    "close": price,
                    "volume": 1.0,
                    "open_timestamp": open_iso,
                    "close_timestamp": close_iso,
                }
            elif forming["open_timestamp"] == open_iso:
                # Update existing forming candle
                forming["high"] = max(forming["high"], price)
                forming["low"] = min(forming["low"], price)
                forming["close"] = price
                forming["volume"] += 1.0
            else:
                # Interval boundary crossed -> close existing candle
                closed_bar = self._finalize_candle(forming, completed=True)
                completed_candles.append(closed_bar)
                self._store_candle(closed_bar)

                # Start new forming candle
                self._forming_candles[key] = {
                    "symbol": sym,
                    "timeframe": tf,
                    "open": price,
                    "high": price,
                    "low": price,
                    "close": price,
                    "volume": 1.0,
                    "open_timestamp": open_iso,
                    "close_timestamp": close_iso,
                }

        return completed_candles

    def _finalize_candle(self, c_dict: dict, completed: bool = True) -> MarketCandle:
        """Convert forming candle dict into immutable MarketCandle domain model with canonical ID."""
        sym = c_dict["symbol"]
        tf_str = c_dict["timeframe"]

        candle_id, canonical_hash = compute_candle_id(
            symbol=sym,
            timeframe=tf_str,
            open_price=c_dict["open"],
            high_price=c_dict["high"],
            low_price=c_dict["low"],
            close_price=c_dict["close"],
            open_timestamp=c_dict["open_timestamp"],
            close_timestamp=c_dict["close_timestamp"],
        )

        checksum = compute_canonical_sha256(
            {
                "close": c_dict["close"],
                "high": c_dict["high"],
                "low": c_dict["low"],
                "open": c_dict["open"],
                "symbol": sym,
                "timeframe": tf_str,
            }
        )

        try:
            tf_enum = MarketTimeframe(tf_str)
        except ValueError:
            tf_enum = MarketTimeframe.M1

        return MarketCandle(
            candle_id=candle_id,
            symbol=sym,
            timeframe=tf_enum,
            open=c_dict["open"],
            high=c_dict["high"],
            low=c_dict["low"],
            close=c_dict["close"],
            volume=c_dict["volume"],
            open_timestamp=c_dict["open_timestamp"],
            close_timestamp=c_dict["close_timestamp"],
            completed=completed,
            checksum=checksum,
            metadata={"source": "LiveCandleBuilder"},
            canonical_hash=canonical_hash,
        )

    def _store_candle(self, candle: MarketCandle) -> None:
        """Store completed candle in memory history and SQLite database."""
        key = (candle.symbol, candle.timeframe.value)
        if key not in self._history:
            self._history[key] = []
        
        # Avoid duplicates in history
        if not any(c.candle_id == candle.candle_id for c in self._history[key]):
            self._history[key].append(candle)
            if len(self._history[key]) > 1000:
                self._history[key].pop(0)

        # Persist to SQLite if db connection is provided
        if self.db_conn:
            with self.db_conn:
                self.db_conn.execute(
                    """
                    INSERT OR REPLACE INTO live_market_candles (
                        candle_id, symbol, timeframe, open, high, low, close, volume,
                        open_timestamp, close_timestamp, completed, checksum, metadata_json, canonical_hash
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
                    """,
                    (
                        candle.candle_id,
                        candle.symbol,
                        candle.timeframe.value,
                        candle.open,
                        candle.high,
                        candle.low,
                        candle.close,
                        candle.volume,
                        candle.open_timestamp,
                        candle.close_timestamp,
                        1 if candle.completed else 0,
                        candle.checksum,
                        json.dumps(candle.metadata, sort_keys=True),
                        candle.canonical_hash,
                    ),
                )

    def get_latest_candle(self, symbol: str, timeframe: str = "1M") -> MarketCandle | None:
        """Get latest forming or completed candle for symbol and timeframe."""
        sym = symbol.strip().upper()
        tf = timeframe.strip().upper()
        key = (sym, tf)

        # 1. Return active forming candle if available
        forming = self._forming_candles.get(key)
        if forming:
            return self._finalize_candle(forming, completed=False)

        # 2. Fall back to memory history
        if key in self._history and len(self._history[key]) > 0:
            return self._history[key][-1]

        # 3. Fall back to SQLite database
        if self.db_conn:
            cursor = self.db_conn.cursor()
            cursor.execute(
                """
                SELECT candle_id, symbol, timeframe, open, high, low, close, volume,
                       open_timestamp, close_timestamp, completed, checksum, metadata_json, canonical_hash
                FROM live_market_candles
                WHERE symbol = ? AND timeframe = ?
                ORDER BY open_timestamp DESC
                LIMIT 1;
                """,
                (sym, tf),
            )
            row = cursor.fetchone()
            if row:
                return MarketCandle(
                    candle_id=row[0],
                    symbol=row[1],
                    timeframe=MarketTimeframe(row[2]),
                    open=row[3],
                    high=row[4],
                    low=row[5],
                    close=row[6],
                    volume=row[7],
                    open_timestamp=row[8],
                    close_timestamp=row[9],
                    completed=bool(row[10]),
                    checksum=row[11],
                    metadata=json.loads(row[12]),
                    canonical_hash=row[13],
                )

        return None

    def get_historical_candles(
        self, symbol: str, timeframe: str = "1M", limit: int = 100
    ) -> list[MarketCandle]:
        """Fetch historical completed candles for symbol and timeframe."""
        sym = symbol.strip().upper()
        tf = timeframe.strip().upper()
        key = (sym, tf)

        # First query SQLite DB if present
        if self.db_conn:
            cursor = self.db_conn.cursor()
            cursor.execute(
                """
                SELECT candle_id, symbol, timeframe, open, high, low, close, volume,
                       open_timestamp, close_timestamp, completed, checksum, metadata_json, canonical_hash
                FROM live_market_candles
                WHERE symbol = ? AND timeframe = ?
                ORDER BY open_timestamp ASC
                LIMIT ?;
                """,
                (sym, tf, limit),
            )
            rows = cursor.fetchall()
            if rows:
                return [
                    MarketCandle(
                        candle_id=r[0],
                        symbol=r[1],
                        timeframe=MarketTimeframe(r[2]),
                        open=r[3],
                        high=r[4],
                        low=r[5],
                        close=r[6],
                        volume=r[7],
                        open_timestamp=r[8],
                        close_timestamp=r[9],
                        completed=bool(r[10]),
                        checksum=r[11],
                        metadata=json.loads(r[12]),
                        canonical_hash=r[13],
                    )
                    for r in rows
                ]

        # Memory history fallback
        if key in self._history:
            return list(self._history[key])[-limit:]

        return []
