"""
Project GOAT v0.9 — Edge Knowledge Graph Enums
"""

from enum import Enum


class NodeType(str, Enum):
    """Scientific Knowledge Graph Node Types."""
    HYPOTHESIS = "HYPOTHESIS"
    EVIDENCE = "EVIDENCE"
    OBSERVATION = "OBSERVATION"
    EXPERIMENT = "EXPERIMENT"
    STATISTICAL_EVALUATION = "STATISTICAL_EVALUATION"
    LIVE_VALIDATION = "LIVE_VALIDATION"
    GOVERNANCE_DECISION = "GOVERNANCE_DECISION"
    DISCOVERED_EDGE = "DISCOVERED_EDGE"
    MICROSTRUCTURE_BEHAVIOR = "MICROSTRUCTURE_BEHAVIOR"
    ARCHIVE = "ARCHIVE"


class RelationshipType(str, Enum):
    """Scientific Knowledge Graph Relationship Link Types."""
    TESTS_HYPOTHESIS = "TESTS_HYPOTHESIS"
    GENERATES_EVIDENCE = "GENERATES_EVIDENCE"
    OBSERVES_BEHAVIOR = "OBSERVES_BEHAVIOR"
    CONDUCTS_EXPERIMENT = "CONDUCTS_EXPERIMENT"
    EVALUATES_STATISTICS = "EVALUATES_STATISTICS"
    VALIDATES_LIVE = "VALIDATES_LIVE"
    DECIDES_GOVERNANCE = "DECIDES_GOVERNANCE"
    DISCOVERS_EDGE = "DISCOVERS_EDGE"
    ARCHIVES_ARTIFACT = "ARCHIVES_ARTIFACT"
    DERIVED_FROM = "DERIVED_FROM"
    SUPPORTS_PROP = "SUPPORTS_PROP"


class ValidationStatus(str, Enum):
    """Knowledge Graph Relationship & Chain Validation Status."""
    VALID = "VALID"
    BROKEN_CHAIN = "BROKEN_CHAIN"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    ORPHAN_NODE = "ORPHAN_NODE"
    CYCLE_DETECTED = "CYCLE_DETECTED"
    DUPLICATE_RELATIONSHIP = "DUPLICATE_RELATIONSHIP"


class PathValidity(str, Enum):
    """Scientific Traversal Path Validity Classification."""
    VALID_SCIENTIFIC_CHAIN = "VALID_SCIENTIFIC_CHAIN"
    INCOMPLETE_CHAIN = "INCOMPLETE_CHAIN"
    INVALID_CHAIN = "INVALID_CHAIN"
